{"name": "State of Survival: Survive the Zombie Apocalypse", "genre": "Strategy", "score": "4.4", "score_num": "1,510,944", "downloads": "10,000,000+", "description": "\"It's been six months since the zombie apocalypse began. The virus has infected the city. Six months of terror, horror, survival, and fighting against zombies. You are a survivor and your friends are in a brave fight against monsters. Build a city that survives the constant waves of zombies. Welcome to the State of Survival. Ready for a strategy survival game!"}
{"name": "Mobile Legends: Bang Bang", "genre": "Action", "score": "4.1", "score_num": "24,768,635", "downloads": "100,000,000+", "description": "Join your friends in a brand new 5v5 MOBA showdown against real human opponents, Mobile Legends: Bang Bang! Choose your  favorite heroes and build the perfect team with your comrades-in-arms! 10-second matchmaking, 10-minute battles. Laning, jungling, tower rushing, team battles, all the fun of PC MOBAs and action games in the palm of your hand! Feed your eSports spirit!"}
{"name": "Last Shelter: Survival", "genre": "Strategy", "score": "4.3", "score_num": "1,493,353", "downloads": "10,000,000+", "description": "To survive or to turn into one of the walking dead, the choice is yours!"}
{"name": "Rise of Empires: Ice and Fire", "genre": "Strategy", "score": "4.1", "score_num": "547,980", "downloads": "10,000,000+", "description": "Real Time Nation vs. Nation medieval strategy war game. Join now! Train your troops and go to war!"}
{"name": "Top War: Battle Game", "genre": "Strategy", "score": "4.1", "score_num": "250,388", "downloads": "10,000,000+", "description": "The Dark Legion is coming! The Tyrant rules the world!"}
{"name": "Battle Warship: Naval Empire", "genre": "Strategy", "score": "3.9", "score_num": "132,899", "downloads": "10,000,000+", "description": "Merry Christmas! Commander\uff01Santa Claus brings a secret gift for you."}
{"name": "Last Day on Earth: Survival", "genre": "Action", "score": "4.3", "score_num": "4,005,409", "downloads": "50,000,000+", "description": "The survival shooter Last Day on Earth is set in a post apocalyptic world: in 2027 the world saw an outbreak of an unknown infection that destroyed almost all the human race. And it didn\u2019t stop there. All those dead started turning into zombies and those few survivors that have resistance in their blood are trying to survive on the ruins of the once great world."}
{"name": "Grand Hotel Mania", "genre": "Adventure", "score": null, "score_num": null, "downloads": "5,000,000+", "description": "Open hotels with the best team!"}
{"name": "Black Desert Mobile", "genre": "Role Playing", "score": "4.1", "score_num": "341,635", "downloads": "10,000,000+", "description": "\"Finally, An Actual Open-World For Mobile\" \u2013TheGamer-"}
{"name": "Random Dice: PvP Defense", "genre": "Strategy", "score": "4.2", "score_num": "449,761", "downloads": "5,000,000+", "description": "\u2605Winner of the 2020 G-Star Honor Awards\u2605"}
{"name": "Match Masters", "genre": "Casual", "score": "4.5", "score_num": "187,573", "downloads": "1,000,000+", "description": "Match 3 games - reinvented! Now with online multiplayer!"}
{"name": "Mobile Legends: Adventure", "genre": "Role Playing", "score": "4.6", "score_num": "561,243", "downloads": "10,000,000+", "description": "Mobile Legends: Adventure is an epic Idle RPG where all the MLBB heroes reunite. Train your squad of 5 and battle fearsome monsters!  Battle your way through Campaign and Tower of Babel! Solve the puzzles of Akashic Ruins and Labyrinth!"}
{"name": "MapleStory M - Open World MMORPG", "genre": "Role Playing", "score": "3.8", "score_num": "71,161", "downloads": "1,000,000+", "description": "MapleStory M, the highly anticipated follow-up to "}
{"name": "Ulala: Idle Adventure", "genre": "Role Playing", "score": "4.4", "score_num": "113,884", "downloads": "1,000,000+", "description": "Whether you\u2019re sleeping, eating, or taking the subway - come play Ulala: Idle Adventure!  Ulala is an idle MMORPG, which brings to life the excitement and adventures of the Stone Age in a fun and social way!"}
{"name": "Manor Matters", "genre": "Adventure", "score": "4.5", "score_num": "153,758", "downloads": "5,000,000+", "description": "Welcome to Castlewood \u2014 an old manor full of mysteries! Why is it abandoned? What\u2019s hidden behind the tapestry? Is the manor really haunted? "}
{"name": "LifeAfter", "genre": "Role Playing", "score": "4.1", "score_num": "508,575", "downloads": "10,000,000+", "description": "LifeAfter Season 3 is coming! Survive, Restart the World!"}
{"name": "KING`s RAID", "genre": "Role Playing", "score": "4.4", "score_num": "222,238", "downloads": "5,000,000+", "description": "Relax and enjoy with cute LINE FRIENDS characters and new King's Raid Lil' Raiders!"}
{"name": "Cooking Diary\u00ae: Best Tasty Restaurant & Cafe Game", "genre": "Simulation", "score": "4.5", "score_num": "867,454", "downloads": "10,000,000+", "description": "Become the chef of your own restaurant in an exciting and FREE time management game! Cooking Diary is the best cooking game recognized by prestigious awards, loved and supported by MILLIONS OF PLAYERS around the world! Caution: this game can cause real culinary fever!"}
{"name": "Knives Out-No rules, just fight!", "genre": "Adventure", "score": "3.4", "score_num": "519,417", "downloads": "10,000,000+", "description": "Season 15 is underway!"}
{"name": "West Game", "genre": "Strategy", "score": "4.3", "score_num": "119,236", "downloads": "5,000,000+", "description": "Do you have what it takes to be crowned in the Wild West! Build your own town, recruit your own gangs and get ready to fight against players from all over the WORLD. "}
{"name": "Redecor - Home Design Game", "genre": "Simulation", "score": "4.5", "score_num": "98,243", "downloads": "1,000,000+", "description": "Start a new creative hobby! Play with home decor styles, express your creativity and improve your design skills.  Have fun while gaining inspiration from a vibrant creative community and apply your new ideas in your real life.  If You like home decor, you will love Redecor!"}
{"name": "Kiss of War", "genre": "Strategy", "score": "4.7", "score_num": "196,912", "downloads": "1,000,000+", "description": "Kiss of War is a war strategy game set in the late modern period. It tells a story about a group of charming women with different pasts fighting against the Invaders with allies. You will play as a Commander in the game. Train powerful troops and recruit beautiful female Officers to lead. Unite other Commanders to eliminate the Invaders and finally achieve world peace by establishing a stronger Guild!"}
{"name": "RULES OF SURVIVAL", "genre": "Action", "score": "3.9", "score_num": "1,811,583", "downloads": "50,000,000+", "description": "Welcome to the brand new RULES OF SURVIVAL arena, where the deathmatch has now been raised to a thrilling epic scale! This is a Battle Royale game now played by over 280 million people worldwide. "}
{"name": "Golf Rival", "genre": "Sports", "score": "4.3", "score_num": "300,645", "downloads": "10,000,000+", "description": "Welcome to the brand-new and fascinating free to play game\u2014\u2014Golf Rival, a multiplayer online golf game. A REAL-TIME 1v1 competition and professional realistic golf equipment will help you get the most out of your extraordinary golf abilities. In addition, the spectacular graphics and abundant scenes will give you an immersive gaming experience. Just DOWNLOAD it now and play with people from all over the world!"}
{"name": "Clockmaker", "genre": "Puzzle", "score": "4.4", "score_num": "321,584", "downloads": "10,000,000+", "description": "Be the hero of the "}
{"name": "Harry Potter: Hogwarts Mystery", "genre": "Adventure", "score": "4.3", "score_num": "2,038,099", "downloads": "10,000,000+", "description": "\ud83e\udd89 Your letter has finally arrived! What kind of witch or wizard will you be? A heroic Gryffindor? A cunning Slytherin? A clever Ravenclaw? A loyal Hufflepuff? YOU decide! \ud83c\udf93 With countless choices, you\u2019ll be able to carve out your own unique path in Harry Potter: Hogwarts Mystery. \ud83d\udcec"}
{"name": "Standoff 2", "genre": "Action", "score": "4.6", "score_num": "3,786,931", "downloads": "50,000,000+", "description": "The legendary \"Standoff\" is back in the form of a dynamic first-person shooter!"}
{"name": "Art of War: Legions", "genre": "Strategy", "score": "4.5", "score_num": "695,696", "downloads": "10,000,000+", "description": " You will be the commander who leads legions of tiny armies. Accept the challenges of various levels and don\u2019t forget to get extra rewards from bounty tasks! It\u2019s your army, you in charge."}
{"name": "Warpath", "genre": "Strategy", "score": "4.4", "score_num": "65,652", "downloads": "1,000,000+", "description": "A pungent stench surfaces as a powerful force takes control... Evil incarnate. Their obsessive training rituals and sickening brainwashing practices have become aggravated. They chant \u201cPurge the scum! Crush the weak!\u201d until daylight. Innocent lives are taken at a frightening pace and once-loyal soldiers turn to the dark as a barbaric army quickly gains power."}
{"name": "KartRider Rush+", "genre": "Racing", "score": "4.0", "score_num": "354,068", "downloads": "10,000,000+", "description": "The kart racing sensation enjoyed by over 300M players worldwide is back and better than ever with more style, more game modes, more thrill! Race with friends or just play it solo through a variety of gameplay modes. Collect and upgrade iconic characters and karts from the KartRider universe. Climb the leaderboard ranks and become the ultimate racing legend!"}
{"name": "EverMerge", "genre": "Puzzle", "score": "4.5", "score_num": "118,090", "downloads": "1,000,000+", "description": "EverMerge is a merge adventure puzzle game built on matching and combining to create one big magical world! "}
{"name": "Chapters: Interactive Stories", "genre": "Simulation", "score": "4.0", "score_num": "313,761", "downloads": "10,000,000+", "description": "Choose your story with Chapters, the interactive story game that lets you choose your path in every story. Read through pages and pages of fun interactive stories that fit your mood, from romance to suspense!"}
{"name": "Game of Sultans", "genre": "Role Playing", "score": "3.9", "score_num": "489,456", "downloads": "10,000,000+", "description": "Rule your empire. Live your glorious life!"}
{"name": "The Seven Deadly Sins: Grand Cross", "genre": "Role Playing", "score": "4.3", "score_num": "393,439", "downloads": "10,000,000+", "description": "Are you ready to enjoy dynamic combat, breathtaking animations, and a riveting story true to the original?"}
{"name": "Game of Thrones: Conquest \u2122 - Strategy Game", "genre": "Role Playing", "score": "4.0", "score_num": "272,356", "downloads": "10,000,000+", "description": "The fight for the Iron Throne still rages on in Game of Thrones: Conquest."}
{"name": "Puzzles & Survival", "genre": "Role Playing", "score": "4.4", "score_num": "45,114", "downloads": "1,000,000+", "description": "The outbreak of a deadly virus swept over the world. Almost all of humanity have turned into zombies. Lead your followers to survive the apocalypse: that is your quest."}
{"name": "8 Ball Pool", "genre": "Sports", "score": "4.4", "score_num": "20,468,787", "downloads": "500,000,000+", "description": "\u2022The World's #1 Pool game - now on Android!\u2022"}
{"name": "Epic Seven", "genre": "Role Playing", "score": "4.3", "score_num": "283,602", "downloads": null, "description": "And thus began the 7th World..."}
{"name": "Lily\u2019s Garden", "genre": "Puzzle", "score": "4.6", "score_num": "941,406", "downloads": "10,000,000+", "description": "Romance? Garden? Puzzles? YES! Lily\u2019s Garden is all this and so much more. Renovate the garden and solve challenging puzzles with this new relaxing and romantic FREE match-3 blast game!"}
{"name": "Fishing Clash", "genre": "Simulation", "score": "4.6", "score_num": "1,218,155", "downloads": "50,000,000+", "description": "High time to go fishing! Join millions of anglers worldwide and start catching fish species in Fishing Clash - a thrilling fishing simulator game! Play 1v1 PvP fishing games and fight for the title of fishing champion!"}
{"name": "Age of Z Origins", "genre": "Strategy", "score": "4.4", "score_num": "314,810", "downloads": "10,000,000+", "description": "Kill zombies, form alliances, and lead human civilization back from the brink of doom in this zombie strategy MMO!"}
{"name": "Matchington Mansion", "genre": "Puzzle", "score": "4.4", "score_num": "1,839,524", "downloads": "50,000,000+", "description": "Decorate your mansion with a match-3 makeover puzzle game! Design new home decor & furniture by matching candy, power-up with levels and renovate your entire house, including your kitchen & garden. Download Matchington Mansion for match 3 makeover madness!"}
{"name": "Evony: The King's Return", "genre": "Strategy", "score": "4.2", "score_num": "230,369", "downloads": "10,000,000+", "description": "Build your cities. Train your troops. Expand your empire. Be the King of 7 kingdoms! "}
{"name": "MARVEL Strike Force - Squad RPG", "genre": "Role Playing", "score": "4.3", "score_num": "505,904", "downloads": "10,000,000+", "description": "In "}
{"name": "\uae30\uc801\uc758 \uac80", "genre": "Role Playing", "score": "4.1", "score_num": "158,769", "downloads": "1,000,000+", "description": "\u25a0\uc774\ubca4\ud2b8 \uc0c1\uc138\ubcf4\uae30: https://m.4399.co.kr/template/event/ms/tiger/m/googleplay.html"}
{"name": "Toon Blast", "genre": "Puzzle", "score": "4.6", "score_num": "3,071,641", "downloads": "50,000,000+", "description": "WELCOME TO THE FUNNIEST CARTOON PUZZLE ADVENTURE!"}
{"name": "Mafia City", "genre": "Strategy", "score": "3.9", "score_num": "891,517", "downloads": "50,000,000+", "description": "\u25b2Compete to become the Godfather in an awesome strategy game that requires wit and time management!"}
{"name": "Project Makeover", "genre": "Casual", "score": "4.1", "score_num": "118,042", "downloads": "10,000,000+", "description": "Give desperately needed makeovers to help people achieve their dreams! Choose highly fashionable clothes, hairstyles, makeup, and even furniture! Deal with dramatic characters like egotistical fashion icons, scheming assistants, or stubborn clients in dire need of a new wardrobe. Play challenging fashion-themed puzzles to help find that perfect look! And don't forget to customize your own signature style with your avatar!"}
{"name": "Rise of Kingdoms: Lost Crusade", "genre": "Strategy", "score": "4.3", "score_num": "1,509,677", "downloads": "10,000,000+", "description": "11 Civilizations, 34 Heroes, Real Warfare"}
{"name": "Genshin Impact", "genre": "Adventure", "score": "4.5", "score_num": "1,045,474", "downloads": "10,000,000+", "description": "Step into Teyvat, a vast world teeming with life and flowing with elemental energy."}
